# Generated by Django 4.2.1 on 2023-05-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
