# Generated by Django 4.2.1 on 2023-05-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credibility',
            field=models.IntegerField(default=0),
        ),
    ]
