# Generated by Django 4.2.1 on 2023-05-28 00:54

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('number', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('holder_nric', models.CharField(blank=True, max_length=50, null=True)),
                ('evidence_score', models.IntegerField(default=0)),
                ('appealed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('evidence', models.FileField(blank=True, null=True, upload_to=core.models.Report.report_document_loc)),
                ('evidence_description', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
