# Generated by Django 4.2.1 on 2023-05-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='evidence_score',
            field=models.IntegerField(default=0),
        ),
    ]
