# Generated by Django 4.2.1 on 2023-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_report_category_alter_report_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='evidence_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
